image: rustlang/rust:nightly

stages:
  - build
  - tests

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - plotlib/

before_script:
  - apt-get update -qqy && apt-get install -qqy git python3-pip python3-dev -qy

build:
  stage: build
  script:
    - git clone https://github.com/ManifoldFR/plotlib
    - cargo build --release  
  artifacts:
    paths:
      - target/release

tests:
  stage: tests
  dependencies:
    - build
  script:
    - cargo test --all --verbose
