image: rustlang/rust:nightly

stages:
  - build
  - tests

before_script:
  - apt-get update -qqy && apt-get install -qqy git python3-pip python3-dev -qy

build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - plotlib/
  artifacts:
    paths:
      - plotlib/
      - target/release

tests:
  stage: tests
  dependencies:
    - build
  script:
    - cargo test --all --verbose


examples:
  stage: tests
  dependencies:
    - build
  script:
    - cd lib/
    - cargo run --example homog_time_poisson
    - cargo run --example variable_poisson
    - cargo run --example hawkes_exp
    - cargo run --example 2d_poisson
  artifacts:
    paths:
      - examples/images/*