image: rust:latest

stages:
  - build
  - run-examples

build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release

examples:
  stage: run-examples
  before_script:
    - apt-get install gnuplot-x11 -y
  script:
    - cargo run --example variable_poisson -- --terminal pngcairo