image: rust:latest

stages:
  - build
  - tests

build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release

tests:
  stage: tests
  script:
    - cargo test -- --nocapture


examples:
  stage: tests
  before_script:
    - apt-get update
    - apt-get install gnuplot-x11 -y
  script:
    - cargo run --example homog_time_poisson -- --terminal pngcairo
    - cargo run --example variable_poisson -- --terminal pngcairo
    - cargo run --example hawkes_exponential -- --terminal pngcairo
    - cargo run --example 2d_poisson