[package]
name = "point-process"
version = "0.1.0"
authors = ["ManifoldFR <manifoldfr@outlook.com>"]
exclude = [
    "test.svg"
]

[dependencies]
rand = "^0.5"

[dev-dependencies]
plotlib = "^0.3"

[lib]
name = "pointprocesses"
path = "src/lib.rs"

[[example]]
name = "variable_poisson"

