[package]
name = "point-process"
version = "0.1.0"
authors = ["ManifoldFR <manifoldfr@outlook.com>"]

[dependencies]
rand = "^0.5"
plotlib = "^0.3"

[lib]
name = "pointprocesses"
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/bin/main.rs"
