[package]
name = "point_process"
version = "0.1.0"
authors = ["ManifoldFR <manifoldfr@outlook.com>"]
description = "A crate for simulating random point processes."
license = "MIT"
exclude = [
    "test.(svg|png)"
]

[dependencies]
rand = "^0.5"

[dev-dependencies]
plotlib = "^0.3"

[lib]
name = "pointprocesses"
path = "src/lib.rs"

[[example]]
name = "variable_poisson"

