[package]
name = "pointprocessespy"
version = "0.1.0"
authors = ["ManifoldFR <manifoldfr@outlook.com>"]

[dependencies]
point_process = { path = "../" }

[dependencies.pyo3]
version = "0.4.0"
features = ["extension-module"]

[lib]
name = "pointprocessespy"
path = "src/lib.rs"
crate-type = ["cdylib"]
