[package]
name = "pointprocessespy"
version = "0.3.0"
authors = ["ManifoldFR <manifoldfr@outlook.com>"]

[dependencies]
point_process = { path = "../lib/" }
numpy = { git = "https://github.com/rust-numpy/rust-numpy" }
ndarray = "0.12.0"

[dependencies.pyo3]
version = "0.5.0-alpha.2"
features = ["extension-module"]

[lib]
name = "pointprocessespy"
path = "src/lib.rs"
crate-type = ["cdylib"]
